export const Routes = {
  Login: "/login",
  SignUp: "/signup",
  ConfirmPassword: "/confirm-password",
  ChangePassword: "/change-password",
  ValidateForgotPassword: "/forgot-password/:id",
  ForgotPassword: "/forgot-password",
  ValidateSignup: "/signup/:id",
  ValidateAgentSignup: "/verify-signup/agent/:id",
  ValidateAdminSignup: "/verify-signup/admin/:id",
  AdminLogin: "/admin/login",
  Home: "/app/home",
  Members: "/app/members",
  ReturnsPayment: "/app/returns-payment",
  Reports: "/app/reports",
  ApprovalChain: "/app/approval-chain",
  Projects: "/app/projects",
  ViewProjects: "/app/project/:id",
  Users: "/app/users",
  Beneficiaries: "/app/beneficiaries",
  AgentSignup: "/signup/agent/:id",
  AgentsProject: "/app/agent/project",
  AgentsProjectCreate: "/app/agent/create"
};
